### ISSUE TITLE
Checking file type

### ISSUE THREAD

**Issue by Lepkoski** [jejung/effacious-duck#4]
Checking only href.endsWith(".pdf") || href.endsWith(".jpg") || href.endsWith(".avi") in the method extract(Element el) from URLExtractor .java wil not work properly because some URLs may contain parameters and thus they don't end with the file extension.
There are times where the URL doesn't even contains the filename, so another aproach is necessary.

**Comment by jejung** [comment]
We have to filter it on open connections, getting the http Content-type parameter. I will see what i can do.
